In [1]:
import sys
print("Python version: {}".format(sys.version))

import pandas as pd
print("pandas version: {}".format(pd.__version__))
import matplotlib
print("matplotlib version: {}".format(matplotlib.__version__))
import numpy as np
print("NumPy version: {}".format(np.__version__))
import scipy as sp
print("SciPy version: {}".format(sp.__version__))
import IPython
print("IPython version: {}".format(IPython.__version__))
import sklearn
print("scikit-learn version: {}".format(sklearn.__version__))

Python version: 3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]
pandas version: 1.0.5
matplotlib version: 3.2.2
NumPy version: 1.18.5
SciPy version: 1.5.0
IPython version: 7.16.1
scikit-learn version: 0.23.1


In [2]:
# A first application: classifiying Iris Species
# We want the computer to determine 
#the species based on the parts of the flower
# supervised learning - classification problem
# each possible output is a class
# three types of irises - 3 classes
from sklearn.datasets import load_iris
iris_dataset = load_iris()

In [4]:
print("Keys of iris_dataset: \n{}".format(iris_dataset.keys()))

Keys of iris_dataset: 
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [5]:
print(iris_dataset['DESCR'][:193]+ "\n...")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, pre
...


In [6]:
print("Target names: {}".format(iris_dataset
                               ['target_names']))

Target names: ['setosa' 'versicolor' 'virginica']


In [8]:
print("Feature names: \n{}".format(iris_dataset['feature_names']))

Feature names: 
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [10]:
print("Type of data: {}".format(type(iris_dataset['data'])))

Type of data: <class 'numpy.ndarray'>


In [11]:
# the rows in the data array correspond to flowers, while 
# the columns represent the four measurements that were taken
# for each flower.
print("Shape of data: {}".format(iris_dataset['data'].shape))

Shape of data: (150, 4)


In [12]:
# 150 rows, 4 columns
print("First five columns of data:\n{}".format(iris_dataset['data'][:5]))

First five columns of data:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [13]:
#From this data, we can see that all of the first five flowers have a petal width of 0.2 cm
#and that the first flower has the longest sepal, at 5.1 cm.
print("Type of target: {}".format(type(iris_dataset['target'])))

Type of target: <class 'numpy.ndarray'>


In [14]:
print("Shape of target: {}".format(iris_dataset['target'].shape))

Shape of target: (150,)


In [15]:
#the following shows that the species are encoded 0 to 2
print("Target:\n{}".format(iris_dataset['target']))


Target:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [16]:
# we'll split the  data into a training set and test data
# the function we'll use is train_test_split
# this function extracts 75% as a training set and the 
# remaining 25% becomes the test set
# Using 25% of data for test set is a good rule of thumb

# data is usually denoted with capital X while labels - 
# lowercase y

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    iris_dataset['data'], iris_dataset['target'], random_state = 0)
# test train split shuffles the dataset - or else it would just
# model the first 75% and not get the unique stuff from the back 
# quarter
# random_state parameter is like set_seed



In [17]:
print("X_train shape: {}".format(X_train.shape))
print("y_train shape: {}".format(y_train.shape))

X_train shape: (112, 4)
y_train shape: (112,)


In [18]:
# X_train has 75% of rows of data

In [19]:
print("X_test shape: {}".format(X_test.shape))
print("y_test shape: {}".format(y_test.shape))

X_test shape: (38, 4)
y_test shape: (38,)


In [24]:
# create dataframe from data in X_train
# label the columns using the strings in iris_dataset.feature_names
pip  mglearn
iris_dataframe = pd.DataFrame(X_train, columns=iris_dataset.feature_names)
# create a scatter matrix from the dataframe, color by y_train
grr = pd.plotting.scatter_matrix(iris_dataframe, c=y_train, figsize=(15, 15), marker='o',
hist_kwds={'bins': 20}, s=60, alpha=.8, cmap=mglearn.cm3)

SyntaxError: invalid syntax (<ipython-input-24-426274986629>, line 3)

In [ ]:
# not able to finish that today

In [34]:
# the first model: k-nearest neighbors
# k signifies that instead of using only the closest neighbor
# to the new data point, we can consider any fixed # k of 
# neighbors in the training (for example, the closest 3 to 5
# neighbors)
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 1)

In [35]:
# knn object encapsulates the algorithm that will be used to
# build the model from the training data, as well as the 
# algorithm to make predictions on new data points.
# we'll use the fit method of the knn object
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [36]:
# that last part doesn't look like page 21 in the book
X_new = np.array([[5,2.9,1,0.2]])
print("X_new.shape: {}".format(X_new.shape))

X_new.shape: (1, 4)


In [37]:
prediction = knn.predict(X_new)
print("Prediction: ()".format(prediction))
print("Predicted target name: {}".format(
    iris_dataset['target_names'][prediction]))

Prediction: ()
Predicted target name: ['setosa']


In [39]:
# cool!
#Our model predicts that it belongs to class 0, setosa
# Compute the accuracy: the fraction of flowers for which
# the right species was predicted:
y_pred = knn.predict(X_test)
print("Test set predictions:\n {}".format(y_pred))

Test set predictions:
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [40]:
print("Test set score: {:.2f}".format(np.mean(y_pred == y_test)))


Test set score: 0.97


In [41]:
print("Test set score: {:.2f}".format(knn.score(X_test, y_test)))
# test accuracy is about 0.97
# made the right model for 97% of the irises in the test set
# under some math assumptions, we can expect our model 
# to be correct 97% of the time
# Finished on page 23

Test set score: 0.97
